# Generated by Django 5.0.6 on 2024-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название статьи'),
            preserve_default=False,
        ),
    ]
